// ====== Alternative 替代品页 ======

export type AlternativeItem = {
  name: string;
  toolSlug?: string;
  emoji: string;
  vendor: string;
  pricing: string;
  rating: number;
  bestFor: string;
  pros: string[];
  cons: string[];
  reasonOverOriginal: string;
};

export type Alternative = {
  slug: string;
  originalName: string;
  originalEmoji: string;
  title: string;
  metaTitle: string;
  metaDesc: string;
  hero: string;
  whyAlternatives: string;
  alternatives: AlternativeItem[];
  faq: { q: string; a: string }[];
};

export const alternatives: Alternative[] = [
  {
    slug: "chatgpt",
    originalName: "ChatGPT",
    originalEmoji: "🤖",
    title: "ChatGPT 替代品 — 8 个真正能替换的 AI 助手",
    metaTitle: "ChatGPT 替代品 2026 — 国产 / 开源 / 免费 替代清单",
    metaDesc: "找 ChatGPT 的国产 / 免费 / 开源替代？子墨实测 8 个真能替换的 AI 助手清单，每个标注最佳使用场景。",
    hero: "国内访问慢、不能用信用卡、月付 $20 嫌贵 — 这些都是想找 ChatGPT 替代的常见原因",
    whyAlternatives:
      "ChatGPT 是 AI 助手开山祖师，但国内用户用起来痛点多：访问需要科学上网、注册要海外手机号、$20/月对部分用户偏贵、中文场景偶尔有翻译腔。这份榜单按使用场景分类，每个替代品标注真实差距，帮你 5 分钟找到适合的方案。",
    alternatives: [
      {
        name: "Claude",
        emoji: "🧠",
        vendor: "Anthropic",
        pricing: "免费 + Pro $20/月",
        rating: 5,
        bestFor: "代码 / 长文 / 写作",
        pros: ["1M 上下文", "代码任务最强", "写作风格更自然"],
        cons: ["国内仍需代理", "不支持图像生成"],
        reasonOverOriginal: "代码 / 写作场景比 ChatGPT 强，定价相同。",
      },
      {
        name: "DeepSeek",
        toolSlug: "deepseek",
        emoji: "🔮",
        vendor: "深度求索",
        pricing: "免费 + API 0.001 元/千 token",
        rating: 5,
        bestFor: "国内最便宜的 GPT-5 级别模型",
        pros: ["国内访问极快", "API 成本 1/10", "开源可商用"],
        cons: ["复杂代码弱于 GPT/Claude", "国际信任仍在建立"],
        reasonOverOriginal: "国内合规 + 1/10 成本 + 90% 效果。",
      },
      {
        name: "豆包",
        toolSlug: "doubao",
        emoji: "🌟",
        vendor: "字节跳动",
        pricing: "免费",
        rating: 4,
        bestFor: "完全免费的国产 ChatGPT",
        pros: ["完全免费", "国内访问最快", "中文优势明显"],
        cons: ["代码弱", "复杂推理一般"],
        reasonOverOriginal: "完全免费 + 国内可用 + 中文母语优势。",
      },
      {
        name: "Kimi",
        toolSlug: "kimi",
        emoji: "🎈",
        vendor: "Moonshot",
        pricing: "免费",
        rating: 4,
        bestFor: "长文档 / 财报 / 论文阅读",
        pros: ["200 万字超长上下文", "免费", "国内访问"],
        cons: ["创意 / 对话弱于豆包"],
        reasonOverOriginal: "ChatGPT 长文场景失败时的最佳替代。",
      },
      {
        name: "Perplexity",
        toolSlug: "perplexity",
        emoji: "🔍",
        vendor: "Perplexity AI",
        pricing: "免费 + Pro $20/月",
        rating: 5,
        bestFor: "AI 搜索引擎 / 调研",
        pros: ["每个答案带引用", "实时联网", "深度调研模式"],
        cons: ["国内访问需代理"],
        reasonOverOriginal: "ChatGPT 联网搜索容易瞎编，Perplexity 全部带引用可追溯。",
      },
      {
        name: "Qwen 通义千问",
        toolSlug: "qwen",
        emoji: "🐉",
        vendor: "阿里",
        pricing: "免费",
        rating: 4,
        bestFor: "国产开源模型最强",
        pros: ["开源可商用", "国内可访问", "Qwen 3 性能领先"],
        cons: ["商业版功能比闭源国产略弱"],
        reasonOverOriginal: "想要开源 + 国产 + 可商用三件套，唯一选择。",
      },
      {
        name: "Gemini",
        emoji: "♊",
        vendor: "Google",
        pricing: "免费 + Advanced $20/月",
        rating: 4,
        bestFor: "Google 生态用户",
        pros: ["1M 上下文", "Google Workspace 集成", "多模态强"],
        cons: ["国内访问需代理", "中文略弱"],
        reasonOverOriginal: "如果你深度用 Gmail / Docs / Sheets，Gemini 集成更顺。",
      },
      {
        name: "Mistral Le Chat",
        emoji: "🐱",
        vendor: "Mistral AI",
        pricing: "免费 + Pro $14.99/月",
        rating: 4,
        bestFor: "欧洲合规 / 隐私敏感场景",
        pros: ["响应速度极快", "欧盟数据合规", "开源版本可用"],
        cons: ["中文弱于其他选项"],
        reasonOverOriginal: "需要欧盟合规或速度优先时的最佳选择。",
      },
    ],
    faq: [
      {
        q: "国内用户最值得用的 ChatGPT 替代是哪个？",
        a: "豆包（免费日常用）+ DeepSeek（API 后端）+ Kimi（长文档）三件套覆盖 95% 场景，全部国内访问、零成本起步。",
      },
      {
        q: "ChatGPT Plus 还值得订吗？",
        a: "如果重度用 GPTs Store / Sora / Voice 模式，仍值。如果主要用文字对话，Claude / DeepSeek 更值。",
      },
      {
        q: "免费的 ChatGPT 替代品够用吗？",
        a: "对绝大多数任务够。豆包 + Kimi + DeepSeek 免费版组合，子墨自己 60% 任务都用免费层完成。",
      },
    ],
  },
  {
    slug: "notion-ai",
    originalName: "Notion AI",
    originalEmoji: "📓",
    title: "Notion AI 替代品 — 笔记 / 写作 AI 助手清单",
    metaTitle: "Notion AI 替代品 2026 — 6 个不依赖 Notion 的 AI 写作助手",
    metaDesc: "Notion AI 觉得贵 / 不想绑定 Notion？子墨整理 6 个独立 AI 写作 / 笔记助手，每月 ¥0-99 起。",
    hero: "Notion AI 月费 $10、绑死 Notion 平台 — 想要更灵活 / 更便宜 / 中文优化的方案",
    whyAlternatives:
      "Notion AI 体验不错，但前提是你已经把 Notion 当主力笔记。如果你不想绑定一个平台，或者觉得 $10/月只为 AI 写作偏贵，下面的替代品按场景帮你找到更合适的工具。",
    alternatives: [
      {
        name: "豆包",
        toolSlug: "doubao",
        emoji: "🌟",
        vendor: "字节跳动",
        pricing: "免费",
        rating: 4,
        bestFor: "完全免费的中文 AI 写作",
        pros: ["完全免费", "中文场景顶级", "豆包写作浏览器插件好用"],
        cons: ["不集成笔记 App"],
        reasonOverOriginal: "完全免费 + 中文优势，单独 AI 写作场景比 Notion AI 更值。",
      },
      {
        name: "Claude",
        emoji: "🧠",
        vendor: "Anthropic",
        pricing: "免费 + Pro $20/月",
        rating: 5,
        bestFor: "长文 / 高质量内容创作",
        pros: ["1M 上下文最适合长文", "Artifacts 直接生成 Markdown", "写作风格自然"],
        cons: ["不直接嵌入笔记"],
        reasonOverOriginal: "写作质量比 Notion AI 高一个档次。",
      },
      {
        name: "Kimi",
        toolSlug: "kimi",
        emoji: "🎈",
        vendor: "Moonshot",
        pricing: "免费",
        rating: 4,
        bestFor: "长文档总结 / 改写",
        pros: ["200 万字超长", "国内访问", "免费"],
        cons: ["创意写作中规中矩"],
        reasonOverOriginal: "处理超长文档（合同/财报）时 Notion AI 直接卡。",
      },
      {
        name: "Obsidian + Smart Connections",
        emoji: "📔",
        vendor: "Obsidian",
        pricing: "免费 + 插件付费",
        rating: 4,
        bestFor: "本地化 + 隐私优先",
        pros: ["所有数据本地", "插件生态丰富", "支持任意 LLM API"],
        cons: ["需要自己配置", "学习成本"],
        reasonOverOriginal: "数据敏感不能上云的人，Obsidian 是唯一答案。",
      },
      {
        name: "Mem.ai",
        emoji: "💭",
        vendor: "Mem Labs",
        pricing: "$10-15/月",
        rating: 4,
        bestFor: "AI 优先的笔记 App",
        pros: ["AI 在笔记之间自动建立连接", "搜索基于语义", "界面简洁"],
        cons: ["中文支持一般"],
        reasonOverOriginal: "比 Notion 更激进地 All in AI，未来感强。",
      },
      {
        name: "飞书文档 + AI",
        emoji: "🚀",
        vendor: "字节",
        pricing: "团队版含",
        rating: 4,
        bestFor: "团队协作 + 中文优化",
        pros: ["和飞书协作打通", "中文写作好", "国内合规"],
        cons: ["需要团队套餐"],
        reasonOverOriginal: "国内团队用，比 Notion 集成度更高。",
      },
    ],
    faq: [
      {
        q: "Notion AI 真的不值吗？",
        a: "如果你已经用 Notion 当主力，$10/月仍然合理。如果你不用 Notion 或只是偶尔想 AI 写东西，单独用豆包 / Claude 更值。",
      },
      {
        q: "中文写作哪个最好？",
        a: "豆包（免费）和 Kimi（免费）日常足够。质量要求高的中长文用 Claude（$20/月）。",
      },
      {
        q: "想要笔记本地化怎么办？",
        a: "Obsidian + Smart Connections 插件 + DeepSeek API 是当前最佳本地组合，月成本 < ¥30。",
      },
    ],
  },
  {
    slug: "cursor",
    originalName: "Cursor",
    originalEmoji: "🖱️",
    title: "Cursor 替代品 — AI 编程编辑器对比",
    metaTitle: "Cursor 替代品 2026 — Claude Code / Cline / v0 / Lovable",
    metaDesc: "Cursor 卡 / 贵 / 想换？子墨整理 7 个 Cursor 替代品，从命令行到全栈生成全覆盖。",
    hero: "Cursor 偶尔卡 / 月费 $20 / 想试试别的形态 — 这是 7 个值得考虑的替代",
    whyAlternatives:
      "Cursor 是顶级 AI 编辑器，但不一定是每个人的最佳选择。复杂工程容易掉控制、命令行党觉得多余、想试 Vibe Coding 全栈生成等都是常见替换理由。下面按场景列出最值得切换的方案。",
    alternatives: [
      {
        name: "Claude Code",
        toolSlug: "claude-code",
        emoji: "⌨️",
        vendor: "Anthropic",
        pricing: "Claude Pro $20/月含",
        rating: 5,
        bestFor: "复杂工程 / 命令行党",
        pros: ["1M 上下文", "Plan + Apply 模式可控", "原生终端"],
        cons: ["命令行学习曲线"],
        reasonOverOriginal: "复杂项目稳定性比 Cursor 高一档。",
      },
      {
        name: "Cline (VSCode 插件)",
        emoji: "📐",
        vendor: "Cline",
        pricing: "免费 + 自带 API",
        rating: 4,
        bestFor: "免费党 + VSCode 用户",
        pros: ["完全免费", "自带任意 LLM API", "Plan 模式像 Claude Code"],
        cons: ["需要配置 API"],
        reasonOverOriginal: "想在 VSCode 里用免费 AI 编程，Cline + DeepSeek 是绝配。",
      },
      {
        name: "Windsurf",
        emoji: "🌊",
        vendor: "Codeium",
        pricing: "$15/月",
        rating: 4,
        bestFor: "Cursor 的同期竞品",
        pros: ["Cascade 模式 + Tab 自动补全好", "比 Cursor 略便宜"],
        cons: ["生态略弱于 Cursor"],
        reasonOverOriginal: "同样形态下更便宜的选项。",
      },
      {
        name: "v0",
        toolSlug: "v0",
        emoji: "🅥",
        vendor: "Vercel",
        pricing: "免费 + $20/月",
        rating: 4,
        bestFor: "前端 / 落地页生成",
        pros: ["React + Tailwind 标准栈", "Vercel 部署一键"],
        cons: ["不是编辑器，是组件生成"],
        reasonOverOriginal: "纯前端 / UI 任务比在 Cursor 里写更快。",
      },
      {
        name: "Lovable",
        toolSlug: "lovable",
        emoji: "💖",
        vendor: "Lovable",
        pricing: "免费 5 项目 + $25/月",
        rating: 4,
        bestFor: "全栈应用 0-1 生成",
        pros: ["对话式生成完整应用", "数据库 / Auth 全包"],
        cons: ["复杂业务需手工接管"],
        reasonOverOriginal: "MVP 阶段比 Cursor 快 5 倍。",
      },
      {
        name: "Aider",
        emoji: "🤖",
        vendor: "Open Source",
        pricing: "免费 + 自带 API",
        rating: 4,
        bestFor: "开源 / 命令行老手",
        pros: ["完全开源", "Git 集成漂亮", "支持任意 LLM"],
        cons: ["UI 简陋"],
        reasonOverOriginal: "极客党 + 命令行党最爱。",
      },
      {
        name: "GitHub Copilot",
        emoji: "🐙",
        vendor: "GitHub",
        pricing: "$10/月",
        rating: 3,
        bestFor: "已经在 VS Code / IDE 里",
        pros: ["集成度高", "便宜", "Microsoft 生态"],
        cons: ["Agent 能力弱于 Cursor", "Tab 补全比 Cursor 差"],
        reasonOverOriginal: "便宜，公司报销可选。",
      },
    ],
    faq: [
      {
        q: "Claude Code 和 Cline 哪个免费替代更好？",
        a: "Claude Code 不免费（需要 $20 Claude Pro）。Cline 是真免费 + 自带 API（DeepSeek API 月成本 ¥30 左右）。预算紧选 Cline。",
      },
      {
        q: "Cursor 的 Tab 补全是不是无法替代？",
        a: "Windsurf 的 Tab 补全和 Cursor 几乎打平。Cline 不带 Tab 补全。GitHub Copilot Tab 一直在迭代但仍不如 Cursor。",
      },
      {
        q: "国内能用这些工具吗？",
        a: "Cursor / Windsurf / Cline 都需要科学上网调用海外 LLM API。如果接 DeepSeek API（国内可达），Cline + DeepSeek 是国内最佳无 VPN 方案。",
      },
    ],
  },
  {
    slug: "midjourney",
    originalName: "Midjourney",
    originalEmoji: "🎨",
    title: "Midjourney 替代品 — AI 图像生成",
    metaTitle: "Midjourney 替代品 2026 — 即梦 / Flux / Ideogram 对比",
    metaDesc: "Midjourney 国内不能用 / 太贵 / Discord 难用？子墨整理 7 个真能替换的 AI 图像生成工具。",
    hero: "Midjourney 国内访问难、必须用 Discord、$10-30/月 — 这些都是想换的常见理由",
    whyAlternatives:
      "Midjourney 在艺术性上仍是天花板，但国内用户痛点不少：访问需要科学上网、必须用 Discord、最低 $10 也不便宜。下面的替代按场景帮你找到适合的方案。",
    alternatives: [
      {
        name: "即梦 Dreamina",
        toolSlug: "dreamina",
        emoji: "🇨🇳",
        vendor: "字节",
        pricing: "免费 + $20/月 VIP",
        rating: 5,
        bestFor: "国内创作者 / 中文 prompt",
        pros: ["国内访问 + 微信支付", "中文 prompt 理解", "免费额度大"],
        cons: ["艺术性略低于 MJ"],
        reasonOverOriginal: "国内用户综合最佳替代。",
      },
      {
        name: "Flux (Fal.ai / Replicate)",
        emoji: "⚡",
        vendor: "Black Forest Labs",
        pricing: "API 按生成量",
        rating: 5,
        bestFor: "API 集成 / 批量生成",
        pros: ["开源可商用", "Pro 模型质量接近 MJ", "API 友好"],
        cons: ["需要自己接 API"],
        reasonOverOriginal: "做产品后端比 MJ 灵活十倍。",
      },
      {
        name: "Ideogram",
        emoji: "✍️",
        vendor: "Ideogram AI",
        pricing: "免费 + $7/月",
        rating: 4,
        bestFor: "带文字的海报 / 平面设计",
        pros: ["文字渲染最强", "$7 起价亲民"],
        cons: ["艺术风格不如 MJ"],
        reasonOverOriginal: "做带中文字的海报，MJ 经常失败，Ideogram 能直接出。",
      },
      {
        name: "通义万相",
        emoji: "🐉",
        vendor: "阿里",
        pricing: "免费",
        rating: 4,
        bestFor: "免费国产替代",
        pros: ["完全免费", "国内访问稳", "中文 prompt"],
        cons: ["质量略低于即梦"],
        reasonOverOriginal: "0 成本国内可用。",
      },
      {
        name: "DALL-E 3 (ChatGPT)",
        emoji: "🎨",
        vendor: "OpenAI",
        pricing: "$20/月 ChatGPT Plus",
        rating: 4,
        bestFor: "已经订了 ChatGPT 的人",
        pros: ["对话式微调", "已包含在 ChatGPT 里"],
        cons: ["艺术性略低于 MJ"],
        reasonOverOriginal: "如果已经付了 ChatGPT Plus，DALL-E 是顺手送的。",
      },
      {
        name: "Stable Diffusion (Local)",
        emoji: "🌊",
        vendor: "Stability AI",
        pricing: "免费",
        rating: 4,
        bestFor: "极客党 / 本地部署",
        pros: ["完全免费", "完全可控", "插件生态丰富"],
        cons: ["需要 GPU + 配置"],
        reasonOverOriginal: "完全免费 + 完全可控，开发者首选。",
      },
      {
        name: "文心一格",
        emoji: "🇨🇳",
        vendor: "百度",
        pricing: "免费",
        rating: 3,
        bestFor: "国内合规场景",
        pros: ["国内合规备案", "免费"],
        cons: ["质量低于即梦"],
        reasonOverOriginal: "需要严格内容合规备案的场景唯一选择。",
      },
    ],
    faq: [
      {
        q: "国内用户首选哪个 Midjourney 替代？",
        a: "即梦 Maestro 模式，无脑选。国内访问 + 中文 prompt + 微信支付 + 接近 MJ 质量四件套全占。",
      },
      {
        q: "Midjourney 真的不能用了吗？",
        a: "技术上仍能用，但需要：科学上网 + Discord 账号 + 国际信用卡。门槛高，且 Discord 操作笨重。",
      },
      {
        q: "Flux 怎么用？",
        a: "Flux 是模型不是产品，需要通过 Fal.ai / Replicate / fal-ai 等平台调 API。子墨在 claimly 里就用 Flux Pro 通过 Fal.ai 生成图片，效果接近 MJ。",
      },
    ],
  },
  {
    slug: "claude",
    originalName: "Claude",
    originalEmoji: "🧠",
    title: "Claude 替代品 — 国产 / 开源 / 免费 选项",
    metaTitle: "Claude 替代品 2026 — DeepSeek / Qwen / Kimi 对比",
    metaDesc: "想找 Claude 的国产 / 免费 / 开源替代？子墨整理 6 个真能替换的 LLM。",
    hero: "Claude 国内访问难、$20/月 不算便宜、API $3/1M tokens 偏贵 — 来看 Claude 替代清单",
    whyAlternatives:
      "Claude 写作 / 代码能力顶级，但国内用户用起来痛点多：访问需代理、注册要海外手机号、API 价格不便宜。这份榜单按使用场景列出真能替换的方案。",
    alternatives: [
      {
        name: "DeepSeek",
        toolSlug: "deepseek",
        emoji: "🔮",
        vendor: "深度求索",
        pricing: "免费 + API 0.001 元/千 token",
        rating: 5,
        bestFor: "国内最强 Claude 平替",
        pros: ["API 1/10 价格", "国内访问", "效果接近 Claude"],
        cons: ["复杂代码任务略弱"],
        reasonOverOriginal: "国内做产品后端，无脑用 DeepSeek。",
      },
      {
        name: "Qwen 通义千问",
        toolSlug: "qwen",
        emoji: "🐉",
        vendor: "阿里",
        pricing: "免费",
        rating: 4,
        bestFor: "开源可商用",
        pros: ["开源可商用", "Qwen 3 性能领先", "支持私有化部署"],
        cons: ["闭源版本生态小于 DeepSeek"],
        reasonOverOriginal: "需要开源的话首选。",
      },
      {
        name: "ChatGPT",
        emoji: "🤖",
        vendor: "OpenAI",
        pricing: "免费 + Plus $20/月",
        rating: 5,
        bestFor: "多模态 / GPTs Store",
        pros: ["多模态最完整", "GPTs 生态丰富"],
        cons: ["代码 / 长文略弱于 Claude"],
        reasonOverOriginal: "如果你需要图像 / 视频 / 浏览，ChatGPT 一站式。",
      },
      {
        name: "Kimi",
        toolSlug: "kimi",
        emoji: "🎈",
        vendor: "Moonshot",
        pricing: "免费",
        rating: 4,
        bestFor: "长文档 / 国内可用",
        pros: ["200 万字超长上下文", "完全免费", "国内访问"],
        cons: ["代码 / 推理弱于 Claude"],
        reasonOverOriginal: "Claude 的 1M 上下文在 Kimi 这里翻倍 + 免费。",
      },
      {
        name: "豆包",
        toolSlug: "doubao",
        emoji: "🌟",
        vendor: "字节",
        pricing: "免费",
        rating: 4,
        bestFor: "完全免费日常用",
        pros: ["完全免费", "国内最快", "中文优势"],
        cons: ["代码 / 复杂任务弱"],
        reasonOverOriginal: "免费日常用 Claude 完全没必要。",
      },
      {
        name: "Gemini",
        emoji: "♊",
        vendor: "Google",
        pricing: "免费 + Advanced $20/月",
        rating: 4,
        bestFor: "Google 生态用户",
        pros: ["1M 上下文", "Workspace 集成"],
        cons: ["国内访问难", "中文略弱"],
        reasonOverOriginal: "Google 全家桶用户的最佳替代。",
      },
    ],
    faq: [
      {
        q: "Claude API 太贵能怎么省？",
        a: "三个方法：1) 用 Claude Haiku（便宜 5 倍）；2) 后端任务切 DeepSeek（便宜 10 倍）；3) Prompt Caching 启用（重复内容 90% 折扣）。",
      },
      {
        q: "国产模型真能替换 Claude 吗？",
        a: "80% 任务能。复杂代码、严肃工程、关键决策仍建议 Claude。中文写作、翻译、总结、客服等场景国产已经追平。",
      },
      {
        q: "Claude Code 有免费替代吗？",
        a: "Cline (VSCode 插件) + DeepSeek API 是最佳免费组合。月成本 ¥30 左右，能覆盖 80% Claude Code 的能力。",
      },
    ],
  },
  {
    slug: "heygen",
    originalName: "HeyGen",
    originalEmoji: "🎭",
    title: "HeyGen 替代品 — AI 数字人视频",
    metaTitle: "HeyGen 替代品 2026 — 国产 / 免费 数字人方案",
    metaDesc: "HeyGen 太贵 / 国内难用？子墨整理 6 个数字人视频生成替代品，从免费到企业级全覆盖。",
    hero: "HeyGen 月费 $24 起、信用卡支付、口型有违和感 — 这是 6 个值得考虑的替代",
    whyAlternatives:
      "HeyGen 是数字人视频生成的明星产品，但国内用户访问 / 支付都不顺，且 $24/月起步对个人用户偏贵。下面按场景列出值得考虑的替代品。",
    alternatives: [
      {
        name: "硅基智能",
        emoji: "🇨🇳",
        vendor: "硅基智能",
        pricing: "¥199/月起",
        rating: 4,
        bestFor: "国内首选数字人",
        pros: ["国内访问", "中文优化", "口型同步好"],
        cons: ["定价偏贵"],
        reasonOverOriginal: "国内用户首选，比 HeyGen 中文场景更顺。",
      },
      {
        name: "腾讯智影",
        emoji: "🐧",
        vendor: "腾讯",
        pricing: "免费 + 增值",
        rating: 4,
        bestFor: "免费试 + 微信生态",
        pros: ["免费额度", "微信视频号集成", "中文优化"],
        cons: ["数字人形象数量少于 HeyGen"],
        reasonOverOriginal: "免费 + 国内访问，新手第一选。",
      },
      {
        name: "D-ID",
        emoji: "🎬",
        vendor: "D-ID",
        pricing: "$5.99/月起",
        rating: 4,
        bestFor: "便宜的国际方案",
        pros: ["比 HeyGen 便宜", "API 友好"],
        cons: ["质量略低于 HeyGen"],
        reasonOverOriginal: "想做海外但预算有限。",
      },
      {
        name: "Synthesia",
        emoji: "🎥",
        vendor: "Synthesia",
        pricing: "$30/月起",
        rating: 4,
        bestFor: "企业培训 / 课程",
        pros: ["企业级质量", "120+ 数字人形象"],
        cons: ["价格更贵"],
        reasonOverOriginal: "企业培训场景比 HeyGen 更专业。",
      },
      {
        name: "HeyGen 替代 - 即梦数字人",
        toolSlug: "dreamina",
        emoji: "🇨🇳",
        vendor: "字节",
        pricing: "$20/月 VIP",
        rating: 4,
        bestFor: "和图像 / 视频生成一体",
        pros: ["和即梦其他功能打通", "中文优化", "国内访问"],
        cons: ["数字人模块功能略少"],
        reasonOverOriginal: "已经订即梦的人，数字人是顺手送。",
      },
      {
        name: "Wav2Lip (Open Source)",
        emoji: "💻",
        vendor: "开源",
        pricing: "免费",
        rating: 3,
        bestFor: "开发者 / 极客",
        pros: ["完全免费", "可商用", "可自托管"],
        cons: ["需要 GPU + 配置", "质量低于商业方案"],
        reasonOverOriginal: "成本敏感 + 有技术能力的开发者首选。",
      },
    ],
    faq: [
      {
        q: "数字人视频会被识别为低质量吗？",
        a: "纯 AI 数字人视频在抖音 / 小红书等平台偶尔会被降权。建议混合真人 + AI 元素（比如真人画面 + AI 配音 + AI 字幕），平台识别难度大。",
      },
      {
        q: "做带货 / 电商口播选哪个？",
        a: "国内电商首选硅基智能（中文专业）。海外 TikTok 电商选 HeyGen（国际口型最自然）。",
      },
      {
        q: "数字人视频版权归谁？",
        a: "用 HeyGen / 硅基智能等付费方案，生成内容版权归你。但建议保留生成记录和原始 prompt，避免争议。",
      },
    ],
  },
];

export function getAlternativeBySlug(slug: string): Alternative | undefined {
  return alternatives.find((a) => a.slug === slug);
}
